title: Mahdi Sarani's Resume
email: mahdasarani1995@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A web developer and WordPress specialist with over 10 years of experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mahdisarani.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
